apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: tasksapp
  ports:
    - port: {{ .Values.service.Port }}
      targetPort: {{ .Values.deployment.containerPort }}
  type: LoadBalancer
